APP_TITLE = "Adaptive Inventory Management System"
APP_DESCRIPTION = "Something something."

EPISODE_LENGTH = 100
MAX_INVENTORY = 100
INITIAL_INVENTORY = 50

MAX_ORDER = 50
MEAN_DEMAND = 20
DEMAND_STD = 8
DEMAND_SPIKE_CHANCE = 0.10
DEMAND_SPIKE_MULTIPLIER = 1.8
SALE_PRICE = 8.0
ORDER_COST = 4.0
HOLDING_COST = 1.0
SHORTAGE_COST = 10.0
